export const events = {
    REGISTER: "register",
    REGISTER_RESULT: "registerResult",
    CREATE_ROOM: "createRoom",
    GET_ROOMS: "getRooms",
    GET_ROOMS_RESPONSE: "getRoomsResponse",
    ENTER_ROOM: "enterRoom",
    ENTER_ROOM_RESPONSE: "enterRoomResponse",
    NEW_PLAYER_JOINED: "newPlayerJoined",
    NEW_ROOM_CREATED: "newRoomCreated",
    CHECK_IF_LOGGED_IN: "checkIfLoggedIn",
    CHECK_IF_LOGGED_IN_RESULT: "checkIfLoggedInResult",
    LEAVE_ROOM: "leaveRoom",
    LEAVE_ROOM_RESPONSE: "leaveRoomResponse",
    PLAYER_LEFT: "playerLeft",
    START_GAME: "startGame",
    START_GAME_RESPONSE: "startGameResponse",
    GET_CARDS: "getCards",
    GET_CARDS_RESPONSE: "getCardsResponse",
    UPDATE_GAME_STATE: "updateGameState",
    DRAW_CARD: "drawCard",
    PLAY_CARD: "playCard",
}